crm/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from leads.views import LandingPage
from agents.views import SignUpView
from campaigns.views import CampaignsListView
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingPage.as_view(), name ='landing-page'),
    path('leads/', include('leads.urls', namespace="leads")),
    path('users/', include('agents.urls', namespace="users")),
    path('login/', LoginView.as_view(), name="login-page"),
    path('logout/', LogoutView.as_view(), name="logout-page"),
    path('create/', SignUpView.as_view(), name="create-page"),
    path('campaigns/', include('campaigns.urls', namespace="campaigns")),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

leads/urls.py
from django.urls import path
from . import views

app_name = "leads"

urlpatterns = [
path('', views.LeadListView.as_view(), name="lead-list"),
path('create/', views.LeadCreateView.as_view(), name="lead-create"),
path('<int:pk>/comments/', views.update_comment,  name="update-comment"),
path('upload/', views.model_form_upload, name="lead-upload"),
path("assign/", views.bulk_assign, name="bulk-assign"),
path('leads/<int:pk>', views.lead_detail, name="lead-detail"),
path('leads/<int:pk>/edit', views.lead_edit, name="lead-edit"),

]

leads/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField

from agents.models import AgentsInfo, UserProfile
from campaigns.models import Campaigns, CampaignCollection

# LeadData model
class LeadData(models.Model):
    """Lead Information Name, Phone Number, email, date create / update etc..."""
    lead_name = models.CharField(max_length=100)
    phone_number = PhoneNumberField(null=False, blank=False, unique=True)
    email = models.CharField(max_length=100)
    date_added = models.DateTimeField(auto_now_add=True)
    last_updated = models.DateTimeField(null=True, blank=True)
    organization = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    agent = models.ForeignKey(AgentsInfo, null=True, blank=True , on_delete=models.SET_NULL)
    status = models.ForeignKey("Status", related_name="leads", null=True, blank=True, on_delete=models.SET_NULL)
    campaign_name = models.ForeignKey(Campaigns, null=True, blank=True , on_delete=models.CASCADE)
    campaign = models.ForeignKey(CampaignCollection, null=True, blank=True , on_delete=models.CASCADE)
    
    def __str__(self):
        return (self.lead_name)

class Status(models.Model):
    name = models.CharField(max_length=30)  # New, Contacted, Converted, Unconverted etc...
    organization = models.ForeignKey(UserProfile, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class Comments(models.Model):

    note = models.TextField()
    agent = models.ForeignKey(AgentsInfo, null=True, blank=True , on_delete=models.SET_NULL)
    status = models.ForeignKey(Status, null=True, blank=True, on_delete=models.SET_NULL)
    lead = models.ForeignKey(LeadData, on_delete=models.CASCADE)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.note} : {self.agent}" 

leads/forms.py
from django import forms
from .models import LeadData, Comments
from django.forms import TextInput, EmailInput, NumberInput, Select, Textarea
from . import models

textBoxStyle = "mb-6 bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
selectBoxStyle = "mb-6 bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"

class LeadEditModelForm(forms.ModelForm):
    class Meta:
        model = LeadData
        fields = [
            'lead_name',
            'email',
        ]
        widgets = {
            'lead_name': TextInput(attrs={
                'class': textBoxStyle,
                'placeholder': 'PhoneNumber'
            }),
            'email': EmailInput(attrs={
                'class': textBoxStyle,
                'placeholder': 'PhoneNumber'
            })
        }


class LeadModelForm(forms.ModelForm):
    class Meta:
        model = LeadData
        fields = [
            'lead_name',
            'email',
            'phone_number',
            'organization',
            'agent',
            'campaign'
        ]
        widgets = {
            'phone_number': TextInput(attrs={
                'class': textBoxStyle,
                'placeholder': 'PhoneNumber'
            })
        }


class CommentModelForm(forms.ModelForm):
    class Meta:
        model = Comments
        fields = (
            'status',
            'note',
        )

        widgets = {
            'status': Select(attrs={
                'class': selectBoxStyle,
                'onchange' : "changer(this)"
            }),
            'note': Textarea(attrs={
                'class': textBoxStyle,
                'placeholder': 'Note'
            })
        }
    def __init__(self, user=None, **kwargs):
        super(CommentModelForm, self).__init__(**kwargs)
        if user.UserPosition.name == "IT Department" or user.UserPosition.name == "Compliance":
            self.fields['status'].queryset =  models.Status.objects.all()
        else:
           self.fields['status'].queryset = models.Status.objects.filter( organization = user.agentsinfo.organization)
            

leads/views.py
from django.shortcuts import render,redirect, HttpResponse,HttpResponseRedirect, get_object_or_404
from django.urls import reverse
from django.http import QueryDict

from django.views.generic import TemplateView, ListView, CreateView

from django.contrib.auth.mixins import LoginRequiredMixin

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from . import models
from . import forms

from agents import models as ag_model

from campaigns import models as cp_model
from campaigns import forms as cp_form

from csv import DictReader

from django.db.models import Q

from datetime import date

import string
import random

from django.utils import timezone

today = date.today()

class LandingPage(TemplateView):
    template_name= 'landing-page.html'


def lead_detail(request, pk):
    lead = get_object_or_404(models.LeadData, pk=pk)
    context = {'lead':lead}

    if request.method == 'GET':
        return render(request, "leads/lead_detail.html", context)
    elif request.method == 'PUT':
        data = QueryDict(request.body).dict()
        form = forms.LeadEditModelForm(data, instance=lead)
        if form.is_valid():
            form.save()
            return render(request, "leads/partial/lead-detail.html", context)
        
        context['form'] = form
        return render(request, "leads/partial/lead-edit.html", context)

def lead_edit(request, pk):
    lead = get_object_or_404(models.LeadData, pk=pk)
    form  = forms.LeadEditModelForm(instance=lead)
    context = {'lead':lead, 'form':form}
    return render(request, "leads/partial/lead-edit.html", context)

def update_comment(request, pk):
    user = request.user.email
    lead  = models.LeadData.objects.get(id=pk)

    try:
        agent = ag_model.AgentsInfo.objects.get(user__email=user)
    except:
        agent = ag_model.User.objects.get(user = user)
    
    form = forms.CommentModelForm(data=request.POST or None, user=request.user)

    
    if request.method == "POST":
        if form.is_valid():
            status_t = (form.cleaned_data['status'])

            comment = form.save(commit=False)
            lead.last_updated = timezone.now()
            comment.agent = agent
            comment.lead = lead
            if status_t is None:
                comment.status = lead.status
                lead.status = lead.status
            else:
                lead.status = models.Status.objects.get(pk=(request.POST.get('status')))


            comment.save()
            lead.save()
            return render(request, "leads/comment_list.html",context={
                "comments": reversed(models.Comments.objects.filter(Q(lead=lead)))
            })
        else:
            return render(request, ("leads:lead-list"), context={
                "form": form
            })
    
    context = {
        "form": form,
        "agent": agent,
        "lead": lead,
        "comments": reversed(models.Comments.objects.filter(Q(lead=lead)))
    }

    return render(request, "leads/note_create.html", context)

class CommentsListView(LoginRequiredMixin,ListView):
    template_name = 'leads/lead_comment.html'
    context_object_name = "comment"


class LeadListView(LoginRequiredMixin,ListView):
    template_name = 'leads/lead_list.html'
    context_object_name = "leads"
    paginate_by = 100

    def get_context_data(self, **kwargs):
        try:
            context = super().get_context_data(**kwargs)
            queryset = context['leads']
            paginator = Paginator(queryset, self.paginate_by)
            page = self.request.GET.get('page')

            try:
                leads = paginator.page(page)
            except PageNotAnInteger:
                leads = paginator.page(1)
            except EmptyPage:
                leads = paginator.page(paginator.num_pages)

            
            if self.request.user.UserPosition.name == "IT Department" or self.request.user.UserPosition.name == "Compliance":
                status = models.Status.objects.all()
            else:
                status = models.Status.objects.filter( organization = self.request.user.agentsinfo.organization)
                
            
            context['leads'] = leads
            context.update({
                "campaigns": cp_model.Campaigns.objects.all(),
                "campaigns_col": cp_model.CampaignCollection.objects.all(),
                "agents" : ag_model.AgentsInfo.objects.all(),  
                "statuses" : status,  
            })
            return context 
        except:
            pass           

    def get_queryset(self):

        filter  = self.request.GET.get('filter')
        search_post = self.request.GET.get('search')
        campaign_id = self.request.GET.getlist('campaign_id')
        agent_id = self.request.GET.getlist('agent_id')
        note_id = self.request.GET.getlist('note_id')
        user = self.request.user
        print(self.request.user.UserPosition.name )

        if self.request.user.UserPosition.name == "IT Department" or self.request.user.UserPosition.name == "Compliance":
            queryset = models.LeadData.objects.all()
        elif self.request.user.UserPosition.name == "Agent":
            queryset  = models.LeadData.objects.filter( organization = user.agentsinfo.organization)
            queryset = queryset.filter(agent__user=user)
        else:
            organization = ag_model.UserProfile.objects.get(user = user)
            queryset  = models.LeadData.objects.filter( organization = organization)

        if search_post:
            if filter == "id":
                queryset = queryset.filter(Q(lead_name__icontains=search_post))
            elif filter == "email":
                queryset = queryset.filter(Q(email=search_post))
            elif filter == "number":
                queryset = queryset.filter(Q(phone_number__icontains=search_post))
        else:
            if filter:
                if campaign_id:
                    queryset = queryset.filter(Q(campaign_name__in=campaign_id))
            
                if agent_id:
                    if "Unassigned" in agent_id :
                        agent_id.remove("Unassigned")
                        queryset =queryset.filter(Q(agent__isnull=True) | Q(agent__in=agent_id))
                    else:   
                        queryset = queryset.filter(Q(agent__in=agent_id))
                
                if note_id:
                    if "Fresh" in note_id:
                        note_id.remove("Fresh")
                        queryset =queryset.filter(Q(status__isnull=True) | Q(status__in=note_id))
                    else:   
                        queryset = queryset.filter(Q(status__in=note_id))

        return queryset.order_by("pk").reverse()


class LeadCreateView(LoginRequiredMixin, CreateView):
    template_name = 'leads/lead_create.html'
    form_class = forms.LeadModelForm

    def get_success_url(self) -> str:
        return (reverse("leads:lead-list"))


def handle_files(csv_file, name, id, og):
    file_name = f"media/leads/{csv_file}"
    duplicates = []
    with open(file_name, 'r', encoding="utf-8-sig") as read_obj:
        csv_reader = DictReader(read_obj)
        for row in csv_reader:
            lead_name = row['name']
            email = row['email']
            try:
                phone_number = row['number']
            except:
                phone_number = row['phone']
            

            try:
                models.LeadData.objects.create(
                    organization=og,
                    lead_name=lead_name.title(),
                    phone_number= f"+{str(phone_number)}",
                    email=email.lower(),
                    campaign = cp_model.CampaignCollection.objects.get(campaign=id),
                    campaign_name = name
                )
            except Exception as e:
                print(e)
                duplicates.append(row)
                
    return len(duplicates)


def id_generator():
    chars=string.ascii_uppercase + string.digits
    size=6
    final = ''.join(random.choice(chars) for _ in range(size))
    return today.strftime("%b-%d-%Y") + final

def model_form_upload(request):
    if request.method == 'POST':
        form = cp_form.CampaignModelForm(request.POST, request.FILES)
        name = cp_model.Campaigns.objects.get(pk = request.POST["name"])
        og = name.organization
        id = f"{name}-{id_generator()}"

        if form.is_valid():
            test = form.save(commit=False)
            test.campaign = id
            name.last_updated = timezone.now()
            duplicates = handle_files(request.FILES['document'], name, id, og)
            test.duplicates = int((duplicates))

            name.save()
            test.save()
            

            return HttpResponseRedirect(reverse("leads:lead-list") )
    else:
        form = cp_form.CampaignModelForm()
    return render(request, 'leads/lead_upload.html', {
        'form': form
    })



def bulk_assign(request):
    if request.method == "POST":
        lead_ids = request.POST.getlist('lead_id')
        agent_id = request.POST.get('agent_id')
        note_id = request.POST.get("note_id")
        qs = models.LeadData.objects.filter(pk__in = lead_ids)

        if note_id:
            if note_id == "Fresh":
                qs.update(status=None)
            else:
                status = models.Status.objects.get(pk = note_id)
                qs.update(status=status)

        if agent_id:
            if agent_id == "Unassign":
                qs.update(agent=None)
            else:
                try:
                    agent = ag_model.AgentsInfo.objects.get(user__id = agent_id)
                    qs.update(agent=agent)

                except Exception as e:
                    print(e)
                
    return HttpResponseRedirect(reverse("leads:lead-list"))

leads/templates/leads/comment_list.html
<section class="text-gray-600 body-font w-full max-h-[32rem] overflow-auto ">
    {% if comments %}
    {% csrf_token %}
    {% for comment in comments %}
    <div class="container w-full py-5 mx-auto">

      <div
        class="flex flex-col items-center mx-auto text-center mx-auto border-b pb-2 mb-2 border-gray-200 dark:border-gray-700 sm:flex-row flex-col">

        <div class="flex flex-col sm:text-left text-center gap-2 mt-6 sm:mt-0">
          <p class="text-sm font-medium text-gray-900 truncate dark:text-white"><i class="fa-solid fa-user mr-2"></i> {{ comment.agent.user.first_name}} {{comment.agent.user.last_name}} ({{ comment.agent}})</p>
          <div class="flex gap-5 items-center">

            <h2 class="inline-flex items-center text-base font-semibold text-gray-500 dark:text-gray-400"><i class="fa-solid fa-calendar-days mr-2"></i> {{ comment.date_added}}</h2>
            {% if comment.status.name == "Follow up" %}
            <span class="bg-blue-100 text-blue-800 text-sm  px-2 py-0.5 rounded ">
              {{comment.status.name}}
            </span>
              {% elif comment.status.name == "No Answer" %}
              <span class="bg-red-100 text-red-800 text-sm  px-2 py-0.5  rounded">
                {{comment.status.name}}
              </span>

              {% elif comment.status.name == "Call Back" %}
              <span class="bg-yellow-100 text-yellow-800 text-sm  px-2 py-0.5  rounded">
                {{comment.status.name}}
              </span>

              {% elif comment.status.name == "Not interested" %}
              <span class="bg-purple-100 text-purple-800 text-sm  px-2 py-0.5  rounded">
                {{comment.status.name}}
              </span>

              {% elif comment.status.name == "Hindi" %}
              <span class="bg-pink-100 text-pink-800 text-sm  px-2 py-0.5  rounded">
                {{comment.status.name}}
              </span>


              {% elif not comment.status %}
              <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-blue-100 text-blue-800">
                Fresh
              </span>

              {% else %}
              <span class="">
                {{lead.status.name}}
              </span>

            {% endif %}

          </div>
            
          <div class="flex gaps-2 items-start justify-center p-2"><i class="fa-solid fa-message p-2"></i><p class="leading-relaxed text-sm w-full text-gray-500 dark:text-gray-400">{{ comment.note }}</p></div>
        </div>
      </div>
    </div>
    {% endfor %}
    {% endif %}
  </section>

leads/templates/leads/lead_create.html
{% extends "base.html"%}
{% load tailwind_filters %}
{% block content%}

<section class="text-gray-600 mt-10  body-font">

<nav class="flex w-1/2 mx-auto mb-5" aria-label="Breadcrumb">
    <ol class="inline-flex items-center space-x-1 md:space-x-3">
      <li class="inline-flex items-center">
        <a href="#" class="inline-flex items-center text-sm font-medium text-gray-700 hover:text-gray-900 ">
          <svg class="w-4 h-4 mr-2" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
            <path
              d="M10.707 2.293a1 1 0 00-1.414 0l-7 7a1 1 0 001.414 1.414L4 10.414V17a1 1 0 001 1h2a1 1 0 001-1v-2a1 1 0 011-1h2a1 1 0 011 1v2a1 1 0 001 1h2a1 1 0 001-1v-6.586l.293.293a1 1 0 001.414-1.414l-7-7z">
            </path>
          </svg>
          Home
        </a>
      </li>
      <li class="inline-flex items-center">
        <a href="{% url 'leads:lead-list' %}" class="inline-flex items-center text-sm font-medium text-gray-700 hover:text-gray-900 ">
            <svg class="w-6 h-6 text-gray-700" fill="currentColor" viewBox="0 0 20 20"
            xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd"
              d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z"
              clip-rule="evenodd"></path>
          </svg>
          Leads
        </a>
      </li>
      <li aria-current="page">
        <div class="flex items-center">
          <svg class="w-6 h-6 text-gray-400" fill="currentColor" viewBox="0 0 20 20"
            xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd"
              d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z"
              clip-rule="evenodd"></path>
          </svg>
          <span class="ml-1 text-sm font-medium text-gray-500 md:ml-2 ">Create</span>
        </div>
      </li>
      
    </ol>
  </nav>
  <hr>

<div class="w-1/2 bg-white flex justify-between text-center mx-auto mt-10 ">
    <h2 class="text-gray-900 text-lg mb-1 font-medium title-font">Create New Lead</h2>
    <p class="leading-relaxed mb-5 text-gray-600">Fill the bellow form.</p>
</div>
<form action="." class="w-1/2 mx-auto" method="post">
    {% csrf_token %}
    {{ form|crispy }}

    <button type="submit"
        class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center ">Submit</button>
</form>
</section>
{% endblock content%}

leads/templates/leads/lead_detail.html
{% extends "base.html"%}

{% block content%}

<div class="mt-20" id="lead-detail">

    {% include "leads/partial/lead-detail.html" %}

</div>

{% endblock content%}

leads/templates/leads/note_create.html
{% extends "base.html"%}
{% load tailwind_filters %}

{% block content%}

<section class="text-gray-600 mt-10  body-font">
  <nav class="flex px-5 py-3 text-gray-700 border border-gray-200 rounded-lg bg-gray-50 dark:bg-gray-800 dark:border-gray-700" aria-label="Breadcrumb">
    <ol class="inline-flex items-center space-x-1 md:space-x-3">
      <li class="inline-flex items-center">
        <a href="#" class="inline-flex items-center text-sm font-medium text-gray-700 hover:text-gray-900 dark:text-gray-400 dark:hover:text-white">
          <svg class="w-4 h-4 mr-2" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M10.707 2.293a1 1 0 00-1.414 0l-7 7a1 1 0 001.414 1.414L4 10.414V17a1 1 0 001 1h2a1 1 0 001-1v-2a1 1 0 011-1h2a1 1 0 011 1v2a1 1 0 001 1h2a1 1 0 001-1v-6.586l.293.293a1 1 0 001.414-1.414l-7-7z"></path></svg>
          Home
        </a>
      </li>
      <li>
        <div class="flex items-center">
          <svg class="w-6 h-6 text-gray-400" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clip-rule="evenodd"></path></svg>
          <a href="{{ request.META.HTTP_REFERER }}" class="ml-1 text-sm font-medium text-gray-700 hover:text-gray-900 md:ml-2 dark:text-gray-400 dark:hover:text-white">Leads</a>
        </div>
      </li>
      <li aria-current="page">
        <div class="flex items-center">
          <svg class="w-6 h-6 text-gray-400" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clip-rule="evenodd"></path></svg>
          <span class="ml-1 text-sm font-medium text-gray-500 md:ml-2 dark:text-gray-400">{{lead}}</span>
        </div>
      </li>
    </ol>
  </nav>
  
  <hr class="my-3 h-px bg-gray-200 border-0 dark:bg-gray-700">

  <h2 class="mb-4 text-3xl font-bold text-center leading-none text-gray-900 md:text-4xl dark:text-white">Update Disposition</h2>
  <ul class="flex flex-wrap justify-center items-center mb-6 text-gray-900 dark:text-white">
    <li  class="mr-4 hover:underline md:mr-6 "><i class="fa-solid fa-user mr-2"></i><span onclick="selectElementContents(this)" class="cursor-pointer ">{{lead}}</span></li>
    <li  class="mr-4 hover:underline md:mr-6 "><i class="fa-solid fa-envelope mr-2"></i><span onclick="selectElementContents(this)" class=" cursor-pointer">{{lead.email}}</span></li>
    <li  class="mr-4 hover:underline md:mr-6 "><i class="fa-solid fa-phone mr-2"></i><span onclick="selectElementContents(this)" class="cursor-pointer ">{{lead.phone_number}}</span></li>
    <li  class="mr-4 hover:underline md:mr-6 "><i class="fa-solid fa-calendar-day mr-2"></i><span class=" ">{{lead.date_added}}</span></li>
  </ul>
  


  <hr class="my-3 h-px bg-gray-200 border-0 dark:bg-gray-700">
  <div class="grid grid-cols-2 ">
    <form hx-post="{% url 'leads:update-comment' lead.pk %}" hx-target='#comments-id' class="form w-full px-10 max-h-[32rem] " method="post">
      {% csrf_token %}
      <label for="id_select" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Select the Status</label>
      {{form.status}}
      <label for="id_note" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Note*</label>
      {{form.note}}
      <button type="submit" hx-post="{% url 'leads:update-comment' lead.pk %}" hx-target='#comments-id'
        class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center ">Submit</button>
      <a href="/leads/?note_id=5&filter=id&search="  class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center ">Show New Leads</a>
    </form>
    <div id="comments-id">{% include 'leads/comment_list.html' %}</div>
    
  </div>
</section>
<script>
  function changer(e){
      document.getElementById('id_note').innerHTML = e.options[e.selectedIndex].text;
    }
  
  var clicked = false;
  $(".all-check").on("click", function () {
    $(".id-check").prop("checked", !clicked);
    clicked = !clicked;
    this.innerHTML = clicked ? 'Deselect' : 'Select';
  });

  function selectElementContents(el) {
    if (window.getSelection && document.createRange) {
      var sel = window.getSelection();
      var range = document.createRange();
      range.selectNodeContents(el);
      sel.removeAllRanges();
      sel.addRange(range);
    } else if (document.selection && document.body.createTextRange) {
      var textRange = document.body.createTextRange();
      textRange.moveToElementText(el);
      textRange.select();
    }
    document.execCommand("copy");
  }
</script>
{% endblock content%}