campaigns/urls.py
from django.urls import path
from . import views

app_name = "campaigns"

urlpatterns = [
path('', views.CampaignsListView.as_view(), name="campaign-list"),
path('create/', views.CampaignsCreateView.as_view(), name="campaign-create"),

]

crm/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from leads.views import LandingPage
from agents.views import SignUpView
from campaigns.views import CampaignsListView
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingPage.as_view(), name ='landing-page'),
    path('leads/', include('leads.urls', namespace="leads")),
    path('users/', include('agents.urls', namespace="users")),
    path('login/', LoginView.as_view(), name="login-page"),
    path('logout/', LogoutView.as_view(), name="logout-page"),
    path('create/', SignUpView.as_view(), name="create-page"),
    path('campaigns/', include('campaigns.urls', namespace="campaigns")),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

leads/urls.py
from django.urls import path
from . import views

app_name = "leads"

urlpatterns = [
path('', views.LeadListView.as_view(), name="lead-list"),
path('create/', views.LeadCreateView.as_view(), name="lead-create"),
path('<int:pk>/comments/', views.update_comment,  name="update-comment"),
path('upload/', views.model_form_upload, name="lead-upload"),
path("assign/", views.bulk_assign, name="bulk-assign"),
path('leads/<int:pk>', views.lead_detail, name="lead-detail"),
path('leads/<int:pk>/edit', views.lead_edit, name="lead-edit"),

]

campaigns/models.py
from django.db import models

from agents.models import UserProfile

class Campaigns(models.Model):
    name = models.CharField(max_length=150)
    created_on = models.DateTimeField(auto_now_add=True)
    last_updated = models.DateTimeField(null=True, blank=True)
    organization = models.ForeignKey(UserProfile,  on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class CampaignCollection(models.Model):
    campaign = models.CharField(max_length=150)
    name = models.ForeignKey(Campaigns, null=True, blank=True , on_delete=models.SET_NULL)
    document = models.FileField(upload_to='leads/')
    uploaded_at = models.DateTimeField(auto_now_add=True)
    duplicates = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return self.campaign

campaigns/forms.py
from django import forms
from . import models
from agents.models import UserProfile

class CampaignModelForm(forms.ModelForm):
    class Meta:
        model = models.CampaignCollection
        fields = ('name', 'document')

class CampaignCreateModelForm(forms.ModelForm):
    class Meta:
        model = models.Campaigns
        fields = ('name', 'organization', )
    
    def __init__(self, user=None, **kwargs):
        super(CampaignCreateModelForm, self).__init__(**kwargs)
        self.fields['organization'].queryset = UserProfile.objects.filter( user__UserPosition__name__icontains = "leader")
            

campaigns/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView, ListView, CreateView
from . import models
from .forms import CampaignModelForm, CampaignCreateModelForm
from django.urls import reverse

class CampaignsListView(LoginRequiredMixin,ListView):
    template_name = 'campaigns/campaign_list.html'
    context_object_name = "campaigns"
    model = models.Campaigns

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            "campaigns_col": models.CampaignCollection.objects.all(),

        })
        return context 


class CampaignsCreateView(LoginRequiredMixin, CreateView):
    template_name = 'campaigns/campaign_create.html'
    form_class = CampaignCreateModelForm

    def get_success_url(self) -> str:
        return (reverse("campaigns:campaign-list"))

campaigns/templates/campaigns/campaign_create.html
{% extends "base.html"%}
{% load tailwind_filters %}
{% block content%}

<section class="text-gray-600 mt-10  body-font">

<nav class="flex w-1/2 mx-auto mb-5" aria-label="Breadcrumb">
    <ol class="inline-flex items-center space-x-1 md:space-x-3">
      <li class="inline-flex items-center">
        <a href="#" class="inline-flex items-center text-sm font-medium text-gray-700 hover:text-gray-900 ">
          <svg class="w-4 h-4 mr-2" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
            <path
              d="M10.707 2.293a1 1 0 00-1.414 0l-7 7a1 1 0 001.414 1.414L4 10.414V17a1 1 0 001 1h2a1 1 0 001-1v-2a1 1 0 011-1h2a1 1 0 011 1v2a1 1 0 001 1h2a1 1 0 001-1v-6.586l.293.293a1 1 0 001.414-1.414l-7-7z">
            </path>
          </svg>
          Home
        </a>
      </li>
      <li class="inline-flex items-center">
        <a href="{% url 'leads:lead-list' %}" class="inline-flex items-center text-sm font-medium text-gray-700 hover:text-gray-900 ">
            <svg class="w-6 h-6 text-gray-700" fill="currentColor" viewBox="0 0 20 20"
            xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd"
              d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z"
              clip-rule="evenodd"></path>
          </svg>
          Leads
        </a>
      </li>
      <li aria-current="page">
        <div class="flex items-center">
          <svg class="w-6 h-6 text-gray-400" fill="currentColor" viewBox="0 0 20 20"
            xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd"
              d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z"
              clip-rule="evenodd"></path>
          </svg>
          <span class="ml-1 text-sm font-medium text-gray-500 md:ml-2 ">Create</span>
        </div>
      </li>
      
    </ol>
  </nav>
  <hr>

<div class="w-1/2 bg-white flex justify-between text-center mx-auto mt-10 ">
    <h2 class="text-gray-900 text-lg mb-1 font-medium title-font">Create New Lead</h2>
    <p class="leading-relaxed mb-5 text-gray-600">Fill the bellow form.</p>
</div>
<form action="." class="w-1/2 mx-auto" method="post">
    {% csrf_token %}
    {{ form|crispy }}

    <button type="submit"
        class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center ">Submit</button>
</form>
</section>
{% endblock content%}

campaigns/templates/campaigns/campaign_list.html
{% extends "base.html"%}
{% load tailwind_filters %}

{% block content%}

{% if campaigns %}
{% csrf_token %}
{% load app_filters %}
<div class="flex mt-10">
  {% if request.user.UserPosition.name != "Agent" %}
  <a href="{% url 'campaigns:campaign-create' %}"
  class="text-white bg-gray-800 hover:bg-gray-900 focus:outline-none focus:ring-4 focus:ring-gray-300 font-medium rounded-l-lg text-sm px-5 py-2  dark:bg-gray-800 dark:hover:bg-gray-700 dark:focus:ring-gray-700 dark:border-gray-700">Create a new campaign</a>

  <a href="{% url 'leads:lead-upload' %}"
  class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-r-lg text-sm px-5 py-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800">Upload
  Lead</a>
  {% endif %}
</div>
  <div class="overflow-x-auto relative shadow-md sm:rounded-lg mt-10">
    <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
        <caption class="p-5 text-lg font-semibold text-left text-gray-900 bg-white dark:text-white dark:bg-gray-800">
            Campaign
           
        </caption>
        <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
            <tr>
                <th scope="col" class="py-3 px-6">
                  Campaign name
                </th>
                <th scope="col" class="py-3 px-6 text-center">
                  Last Uploaded on
                </th>
                <th scope="col" class="py-3 px-6 text-center">
                  Created On
                </th>
                <th scope="col" class="py-3 px-6 text-center">
                  Total Leads
                </th>
                <th scope="col" class="py-3 px-6 text-center">
                  Unassigned Leads
                </th>
                <th scope="col" class="py-3 px-6 text-center">
                  Total Duplicates
                </th>
                <th scope="col" class="py-3 px-6 text-center">
                    <span class="sr-only">Edit</span>
                </th>
            </tr>
        </thead>
        <tbody>
          {% for campaign in campaigns %}
            <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
                <th scope="row" class="py-4 px-6 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                  {{ campaign.name}}
                </th>
                <td class="py-4 px-6 text-center">
                  {{ campaign.last_updated}}
                </td>
                <td class="py-4 px-6 text-center">
                  {{ campaign.created_on}}
                </td>
                <td class="py-4 px-6 text-center">
                  {{ campaign|count_leads}}
                </td>
                <td class="py-4 px-6 text-center">
                  {{ campaign|count_unassign_leads}}
                </td>
                <td class="py-4 px-6 text-center">
                  {{ campaign|count_duplicates}}
                </td>
                
                <td class="py-4 px-6 text-right">
                    <a href="#" class="font-medium text-blue-600 dark:text-blue-500 hover:underline">Edit</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{%endif%}


{%endblock%}