agents/urls.py
from django.urls import path
from .views import AgentListView, AgentCreateView

app_name = "users"
urlpatterns = [
    path('', AgentListView.as_view(), name='agent-list'),
    path('create/', AgentCreateView.as_view(), name="agent-create"),
]

crm/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from leads.views import LandingPage
from agents.views import SignUpView
from campaigns.views import CampaignsListView
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingPage.as_view(), name ='landing-page'),
    path('leads/', include('leads.urls', namespace="leads")),
    path('users/', include('agents.urls', namespace="users")),
    path('login/', LoginView.as_view(), name="login-page"),
    path('logout/', LogoutView.as_view(), name="logout-page"),
    path('create/', SignUpView.as_view(), name="create-page"),
    path('campaigns/', include('campaigns.urls', namespace="campaigns")),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

agents/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.signals import post_save
from django.utils import timezone
from django.contrib.humanize.templatetags.humanize import naturaltime
from django.utils.translation import gettext_lazy as _
from django.core.cache import cache  
import datetime
from crm import settings
 
class UserPosition(models.Model):
    """Represents the user positions like Directors, IT, Agents etc..."""
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class User(AbstractUser):
    """User Model adding position"""
    UserPosition = models.ForeignKey(
        UserPosition,
        related_name="user_position",
        null=True,
        blank=True,
        on_delete=models.SET_NULL)
    
    last_online = models.DateTimeField(blank=True, null=True)
 

class CallBackRemainder(models.Model):
    remainder_time = models.DateTimeField(blank=True, null=True)
    is_done = models.BooleanField(default=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    Lead_id = models.IntegerField(default=0)


class UserProfile(models.Model):

    """Represents the profile where the user is admitted,
    Classifying leads accordingly"""

    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE
        )
    def __str__(self):
        return self.user.username
    
    def last_seen(self):
        return cache.get('seen_%s' % self.user.username)

    def online(self):
        if self.last_seen():
            now = datetime.datetime.now()
            if now > self.last_seen() + datetime.timedelta(
                        seconds=settings.USER_ONLINE_TIMEOUT):
                return False
            else:
                return True
        else:
            return False 



class AgentsInfo (models.Model):
    organization = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    def __str__(self):
        return self.user.email



def post_user_created_signal(sender, instance, created, **kwargs):

    """Simulates the user profile action automatically
    when the user is created"""
    if created:
        UserProfile.objects.create(user=instance)


post_save.connect(post_user_created_signal, sender=User)

agents/forms.py
from django import forms
from leads.models import AgentsInfo
from django.contrib.auth.forms import UserCreationForm, UsernameField
from .models import User

class AgentModelForm(forms.ModelForm):
    class Meta:
        model = AgentsInfo
        fields = (
            'user',
            'organization',
        )

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = (
            'first_name',
            "last_name",
            "username",
            "email",
            "UserPosition"
        )
        field_classes = {"username": UsernameField}

agents/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from leads.models import AgentsInfo, UserProfile
from django.views.generic import ListView, CreateView
from django.urls import reverse
from .forms import AgentModelForm, CustomUserCreationForm



class SignUpView(CreateView):
    template_name= 'registration/signup.html'
    form_class = CustomUserCreationForm

    def get_success_url(self) -> str:
        return (reverse("login-page"))

class AgentListView(LoginRequiredMixin, ListView):
    template_name = "agents/agent_list.html"
    
    def get_queryset(self):
        position = self.request.user.UserPosition.name

        position_list = ['IT Department', "Compliance", "Sales Leader", "Director"]
        if position in position_list:
            return UserProfile.objects.all()
        else:
            organization = self.request.user.userprofile
            return AgentsInfo.objects.filter(organization=organization)


class AgentCreateView(LoginRequiredMixin, CreateView):
    template_name = "agents/agent_create.html"
    form_class = AgentModelForm

    def get_success_url(self):
        return reverse("users:agent-list")

    def form_valid(self, form):
        form.save()
        return super(AgentCreateView, self).form_valid(form)

agents/templates/agents/agent_create.html
{% extends "base.html"%}
{% load tailwind_filters %}

{% block content%}
<div class="lg:w-1/3 md:w-1/2 bg-white flex flex-col md:ml-auto w-full md:py-8 mt-8 md:mt-0"></div>
<h2 class="text-gray-900 text-lg mb-1 font-medium title-font">Create New Agent</h2>
<p class="leading-relaxed mb-5 text-gray-600">Fill the bellow form.</p>

<form action="." class="form" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button  class="text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg" type="submit">Submit</button>
</form>
</div>
{% endblock content%}

agents/templates/agents/agent_list.html
{% extends "base.html"%}

{% block content%}

<section class="text-gray-600 body-font">
  <div class="container px-5 mx-auto">
    <div class="container px-5 mx-auto flex flex-wrap">
      <div class="w-full mb-6 py-6 flex justify-between items-center border-b border-gray-200">
          <div>
              <h1 class="text-4xl text-gray-800">Users</h1>
          </div>
          <div class="flex gap-2">
            <a class="text-gray-500 hover:text-blue-500 pr-2 border-r-2" href="{% url 'users:agent-create' %}">Create a New Agent</a>
              <a class="text-gray-500 hover:text-blue-500" href="{% url 'create-page' %}">Create a New User</a>
          </div>
      </div>

    <div class=" overflow-x-auto relative shadow-md sm:rounded-lg">
      <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
        <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
          <tr>
            <th scope="col" class="p-4 text-center">
              <div class="flex items-center">
                <input id="checkbox-all-search" type="checkbox"
                  class="all-check w-4 h-4 border border-gray-300 rounded bg-gray-50 focus:ring-3 focus:ring-blue-300 dark:bg-gray-700 dark:border-gray-600 dark:focus:ring-blue-600 dark:ring-offset-gray-800 ">
                <label for="checkbox-all-search" class="sr-only">checkbox</label>
              </div>
            </th>
            <th
            scope="col" class="p-4 text-center">
              ID</th>
            <th
            scope="col" class="p-4 text-center">
              Name</th>
            <th scope="col" class="p-4 text-center">Email</th>
            <th scope="col" class="p-4 text-center">Position</th>
            <th scope="col" class="p-4 text-center">Last Seen</th>
            <th scope="col" class="p-4 text-center">Status</th>

          </tr>
        </thead>
        <tbody>
          {% for agent in object_list %}
          
          <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600">
            <td class="p-4 w-4 text-center">
              <div class="flex items-center">
                <input id="checkbox-table-search-1" type="checkbox" value="{{ agent.user.pk }}" name="agent_id"
                  class=" id-check w-4 h-4 border border-gray-300 rounded bg-gray-50 focus:ring-3 focus:ring-blue-300 dark:bg-gray-700 dark:border-gray-600 dark:focus:ring-blue-600 dark:ring-offset-gray-800 ">
                <label for="checkbox-table-search-1" class="sr-only">checkbox</label>
              </div>
            </td>
            

            <td class="py-2 px-6 mx-auto text-center ">{{ agent.user.pk}}</td>
            <td class="py-2 px-6 mx-auto truncate max-w-30 text-center"><a
                href="">{{ agent.user.first_name }} {{ agent.user.last_name }}</a></td>
            <td class="py-2 px-6 mx-auto truncate max-w-30 text-center">{{ agent.user.email }}</td>
            <td class="py-2 px-6 mx-auto truncate max-w-30 text-center">{{ agent.user.UserPosition }}</td>

            <td class="py-2 px-6 mx-auto truncate max-w-30 text-center">{% if agent.last_seen %}{{ agent.last_seen|timesince }}{% else %}awhile{% endif %} ago</td>
            <td class="py-2 px-6 mx-auto truncate max-w-30 items-center">
              <div class="relative">
                {% if agent.online %}
                <span class="absolute w-3.5 h-3.5 bg-green-400 rounded-full"></span>
            
            {% else %}

            <span class="absolute w-3.5 h-3.5 bg-red-400 rounded-full"></span>
              {% endif %}
            </div>

            </td>
          </tr>

          {% endfor%}
        </tbody>
      </table>
    </div>
  </div>
</section>
{% endblock content%}