agents/urls.py
from django.urls import path
from .views import AgentListView, AgentCreateView

app_name = "users"
urlpatterns = [
    path('', AgentListView.as_view(), name='agent-list'),
    path('create/', AgentCreateView.as_view(), name="agent-create"),
]

campaigns/urls.py
from django.urls import path
from . import views

app_name = "campaigns"

urlpatterns = [
path('', views.CampaignsListView.as_view(), name="campaign-list"),
path('create/', views.CampaignsCreateView.as_view(), name="campaign-create"),

]

crm/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from leads.views import LandingPage
from agents.views import SignUpView
from campaigns.views import CampaignsListView
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingPage.as_view(), name ='landing-page'),
    path('leads/', include('leads.urls', namespace="leads")),
    path('users/', include('agents.urls', namespace="users")),
    path('login/', LoginView.as_view(), name="login-page"),
    path('logout/', LogoutView.as_view(), name="logout-page"),
    path('create/', SignUpView.as_view(), name="create-page"),
    path('campaigns/', include('campaigns.urls', namespace="campaigns")),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

leads/urls.py
from django.urls import path
from . import views

app_name = "leads"

urlpatterns = [
path('', views.LeadListView.as_view(), name="lead-list"),
path('create/', views.LeadCreateView.as_view(), name="lead-create"),
path('<int:pk>/comments/', views.update_comment,  name="update-comment"),
path('upload/', views.model_form_upload, name="lead-upload"),
path("assign/", views.bulk_assign, name="bulk-assign"),
path('leads/<int:pk>', views.lead_detail, name="lead-detail"),
path('leads/<int:pk>/edit', views.lead_edit, name="lead-edit"),

]

templates/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <script src="https://unpkg.com/flowbite@1.5.4/dist/flowbite.js"></script>
    <link rel="stylesheet" href="https://unpkg.com/flowbite@1.5.4/dist/flowbite.min.css" />

    <script src="https://code.jquery.com/jquery-3.6.1.min.js" integrity="sha256-o88AwQnZB+VDvE9tvIXrMQaPlFFSUTR+nldQm1LuPXQ=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css">
    <script src="https://unpkg.com/htmx.org@1.8.4"></script>

    <title>Arceus CRM</title>
    <script>
        tailwind.config = {
          theme: {
            extend: {
                maxWidth: {
                    '3': '3rem',
                    '5': '10rem',
                }
            }
          }
        }
      </script>

</head>
<body >
    <div class="max-w-screen py-2 px-5 flex flex-col mx-auto min-h-full dark:bg-gray-900">
        {% include "navbar.html" %}
        {% include "sidebar.html" %}
        {% block content %}
    
    
        {% endblock content %}
    </div>
    <script>
        document.body.addEventListener('htmx:configRequest', (event) => {
            event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}'; //insert csrf token when performing AJAX request 
        })

       
        </script>
</body>
</html>

templates/landing-page.html
{% extends "base.html" %}

{% block content %}


<section class="text-gray-600 body-font">
    <div class="container mx-auto flex px-5 py-24 items-center justify-center flex-col">
      <div class="text-center lg:w-2/3 w-full">
        <h1 class="title-font sm:text-4xl text-3xl mb-4 font-medium text-gray-900">ARCEUS CRM</h1>
        <p class="mb-8 leading-relaxed">Please login to continue</p>
        <div class="flex justify-center">
          <a href="/login" class="inline-flex text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg">Login</a>
        </div>
      </div>
    </div>
  </section>


{% endblock content %}

templates/navbar.html
<nav class=" p-3 border-gray-200 rounded bg-gray-50 dark:bg-gray-800 dark:border-gray-700">
    <div class="container flex flex-wrap items-center justify-between mx-auto">
      <a href="#" class="flex items-center">
          <h1 class="mb-4 text-3xl font-bold text-gray-900 dark:text-white md:text-4xl">Arceus crm</h1>
      </a>
      
      <div class="flex gap-4">
        <button id="dropdownNotificationButton" data-dropdown-toggle="dropdownNotification" class="inline-flex items-center text-sm font-medium text-center text-gray-500 hover:text-gray-900 focus:outline-none " type="button"> 
            <svg class="w-6 h-6" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M10 2a6 6 0 00-6 6v3.586l-.707.707A1 1 0 004 14h12a1 1 0 00.707-1.707L16 11.586V8a6 6 0 00-6-6zM10 18a3 3 0 01-3-3h6a3 3 0 01-3 3z"></path></svg>
            <div class="flex relative">
              <div class="inline-flex relative -top-2 right-3 w-3 h-3 bg-red-500 rounded-full border-2 border-white "></div>
            </div>
            </button>
            <!-- Dropdown menu -->
            <div id="dropdownNotification" class="hidden z-20 w-full max-w-sm bg-white rounded divide-y divide-gray-100 shadow " aria-labelledby="dropdownNotificationButton">
              <div class="block py-2 px-4 font-medium text-center text-gray-700 bg-gray-50 ">
                  Notifications
              </div>
              <div class="divide-y divide-gray-100 dark:divide-gray-700">
                <a href="#" class="flex py-3 px-4 hover:bg-gray-100 ">
                  <div class="flex-shrink-0">
                    <i class="fa-solid fa-circle-user text-4xl"></i>
                  </div>
                  <div class="pl-3 w-full">
                      <div class="text-gray-500 text-sm mb-1.5"><span class="font-semibold text-gray-900 ">User</span>: Got a sale</div>
                      <div class="text-xs text-blue-600 ">time</div>
                  </div>
                </a>
              </div>
              <a href="#" class="block py-2 text-sm font-medium text-center text-gray-900 bg-gray-50 hover:bg-gray-100 ">
                <div class="inline-flex items-center ">
                  <svg class="mr-2 w-4 h-4 text-gray-500 " aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M10 12a2 2 0 100-4 2 2 0 000 4z"></path><path fill-rule="evenodd" d="M.458 10C1.732 5.943 5.522 3 10 3s8.268 2.943 9.542 7c-1.274 4.057-5.064 7-9.542 7S1.732 14.057.458 10zM14 10a4 4 0 11-8 0 4 4 0 018 0z" clip-rule="evenodd"></path></svg>
                    View all
                </div>
              </a>
            </div>
            <div class="relative hidden md:block">
              <div class="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none">
                <svg class="w-5 h-5 text-gray-500" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z" clip-rule="evenodd"></path></svg>
                <span class="sr-only">Search icon</span>
              </div>
              <input type="text" id="search-navbar" class="block w-full p-2 pl-10 text-sm text-gray-900 border border-gray-300 rounded-lg bg-gray-50 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Search...">
            </div>
            
      <button data-drawer-target="drawer-disable-body-scrolling" data-drawer-show="drawer-disable-body-scrolling" data-drawer-body-scrolling="false" aria-controls="drawer-disable-body-scrolling" type="button"  aria-controls="navbar-hamburger" aria-expanded="false" class="inline-flex items-center p-2 ml-3 text-sm text-gray-500 rounded-lg hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" >
        <span class="sr-only">Open main menu</span>
        <svg class="w-6 h-6" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z" clip-rule="evenodd"></path></svg>
      </button>

    </div>
    </div>
  </nav>

templates/sidebar.html
<div id="drawer-disable-body-scrolling" class="fixed z-40 h-screen p-4 overflow-y-auto bg-white w-80 " tabindex="-1"
   aria-labelledby="drawer-disable-body-scrolling-label">
   <div class="flex flex-col h-full justify-between space-y-4">
   <div>
   <h5 id="drawer-disable-body-scrolling-label" class="text-base font-semibold text-gray-500 uppercase ">Menu</h5>
   <button type="button" data-drawer-dismiss="drawer-disable-body-scrolling"
      aria-controls="drawer-disable-body-scrolling"
      class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm p-1.5 absolute top-2.5 right-2.5 inline-flex items-center ">
      <svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20"
         xmlns="http://www.w3.org/2000/svg">
         <path fill-rule="evenodd"
            d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z"
            clip-rule="evenodd"></path>
      </svg>
      <span class="sr-only">Close menu</span>
   </button>
   <div class="py-4 overflow-y-auto">
      <ul class="space-y-2">
         <li>
            <a href="#"
               class="flex items-center p-2 text-base font-normal text-gray-900 transition duration-75 rounded-lg group hover:bg-gray-100 ">
               <i class="fa-solid fa-chart-pie text-gray-500 transition duration-75"></i>
               <span class="ml-3">Dashboard</span>
            </a>
         </li>
         <li>
            <a href="{% url 'leads:lead-list' %}"
               class="flex items-center p-2 text-base font-normal text-gray-900 transition duration-75 rounded-lg group hover:bg-gray-100 ">
               <i class="fa-solid fa-user-tag text-gray-500 transition duration-75"></i>
               <span class="ml-3">Leads</span>
            </a>
         </li>
         {% if request.user.UserPosition.name != 'Agent' %}
         <li>
            <a href="{% url 'users:agent-list' %}"
               class="flex items-center p-2 text-base font-normal text-gray-900 transition duration-75 rounded-lg group hover:bg-gray-100 ">
               <i class="fa-solid fa-users text-gray-500 transition duration-75"></i>
               <span class="ml-3">Users</span>
            </a>
         </li>
         <li>
            <a href="{% url 'campaigns:campaign-list' %}"
               class="flex items-center p-2 text-base font-normal text-gray-900 rounded-lg  hover:bg-gray-100 ">
               <i class="fa-solid fa-tent text-gray-500 transition duration-75"></i>
               <span class="flex-1 ml-3 whitespace-nowrap">Campaign</span>
               <span
                  class="inline-flex items-center justify-center px-2 ml-3 text-sm font-medium text-gray-800 bg-gray-200 rounded-full ">dev</span>
            </a>
         </li>
         <li>
            <button type="button"
               class="flex items-center w-full p-2 text-base font-normal text-gray-900 transition duration-75 rounded-lg group hover:bg-gray-100 "
               aria-controls="dropdown-example" data-collapse-toggle="dropdown-example">
               <i class="fa-solid fa-chart-line text-gray-500 transition duration-75 group-hover:text-gray-900"></i>
               <span class="flex-1 ml-3 text-left whitespace-nowrap">Review</span>
               <svg class="w-6 h-6" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                  <path fill-rule="evenodd"
                     d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z"
                     clip-rule="evenodd"></path>
               </svg>
            </button>
            <ul id="dropdown-example" class="hidden py-2 space-y-2">
               <li>
                  <a href="#"
                     class="flex items-center w-full p-2 text-base font-normal text-gray-900 transition duration-75 rounded-lg pl-11 group hover:bg-gray-100 ">Lead</a>
               </li>
               <li>
                  <a href="#"
                     class="flex items-center w-full p-2 text-base font-normal text-gray-900 transition duration-75 rounded-lg pl-11 group hover:bg-gray-100">Campaign</a>
               </li>
               <li>
                  <a href="#"
                     class="flex items-center w-full p-2 text-base font-normal text-gray-900 transition duration-75 rounded-lg pl-11 group hover:bg-gray-100 ">Agent</a>
               </li>
            </ul>
         </li>
         
         {% endif %}
         <li>
            <a href="#"
               class="flex items-center p-2 text-base font-normal text-gray-900 rounded-lg  hover:bg-gray-100 ">
               <i class="fa-solid fa-calendar-day text-gray-500 transition duration-75"></i>
               <span class="flex-1 ml-3 whitespace-nowrap">Calender</span>
               <span
                  class="inline-flex items-center justify-center px-2 ml-3 text-sm font-medium text-gray-800 bg-gray-200 rounded-full ">dev</span>
            </a>
         </li>
         <li>
            <a href="#"
               class="flex items-center p-2 text-base font-normal text-gray-900 rounded-lg e hover:bg-gray-100 ">

               <i class="fa-solid fa-message text-gray-500 transition duration-75"></i>
               <span class="flex-1 ml-3 whitespace-nowrap">Message</span>
               <span
                  class="inline-flex items-center justify-center w-3 h-3 p-3 ml-3 text-sm font-medium text-blue-600 bg-blue-200 rounded-full ">3</span>
            </a>
         </li>
      </ul>
   </div>
</div>
   {% if request.user.is_authenticated %}
      <div class="flex items-center space-x-4">
         <div class="flex-shrink-0">
            <i class="fa-solid fa-circle-user text-4xl"></i>
         </div>
         <div class="flex-1 min-w-0">
            <p class="text-sm font-medium text-gray-900 truncate ">
               {{request.user.first_name}} {{request.user.last_name}}
            </p>
            <p class="text-sm text-gray-500 truncate">
               {{request.user.email}}
            </p>
         </div>
         
         <a href="{% url 'logout-page' %}" class="inline-flex items-center text-base font-semibold text-gray-900 ">
            logout
      </a>
      </div>
   {% endif %}
</div>
</div>